// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Library.Data;

#nullable disable

namespace Web_Library.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260121135047_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Library.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5cebf85-e61a-4e95-b688-a2b0e6893bed"),
                            Author = "J.R.R. Tolkien",
                            Genre = 0,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("eeb61727-49d9-4b67-a836-1d3eacc4f08d"),
                            Author = "George Orwell",
                            Genre = 1,
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("cda5bf3e-e99c-4a9a-bc3c-889ec28b7031"),
                            Author = "Aldous Huxley",
                            Genre = 1,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = new Guid("f057357a-d690-48ce-a4cc-e1a9748cc63c"),
                            Author = "Robert C. Martin",
                            Genre = 7,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("43f42ae2-7f5f-4944-871e-52d9fd057e6a"),
                            Author = "Andrew Hunt",
                            Genre = 7,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = new Guid("5571dd6b-512c-4d64-8620-cf469800d93c"),
                            Author = "Dan Brown",
                            Genre = 11,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = new Guid("e2c70baa-d665-4ace-9409-6b053e41ed4f"),
                            Author = "Arthur Conan Doyle",
                            Genre = 2,
                            Title = "Sherlock Holmes"
                        },
                        new
                        {
                            Id = new Guid("3fb3a2e4-5968-4eac-9838-eec211167561"),
                            Author = "Stephen King",
                            Genre = 4,
                            Title = "It"
                        },
                        new
                        {
                            Id = new Guid("65f62571-ee92-4e56-b6b9-dd7a8efe8e3f"),
                            Author = "Stephen King",
                            Genre = 4,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = new Guid("8c263c22-48fd-4ecd-9aa9-e01f2d8c0745"),
                            Author = "Paulo Coelho",
                            Genre = 8,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = new Guid("f315b770-aba6-4dd3-b9f0-c8b3d0dce787"),
                            Author = "Yuval Noah Harari",
                            Genre = 6,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = new Guid("4a8a88ba-79f6-44d6-8701-0c4d6bd7e412"),
                            Author = "Yuval Noah Harari",
                            Genre = 6,
                            Title = "Homo Deus"
                        },
                        new
                        {
                            Id = new Guid("ed7d0f41-9d87-4c33-a0c7-3620ed591fe3"),
                            Author = "Walter Isaacson",
                            Genre = 5,
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            Id = new Guid("4f73e635-6290-4152-8c9b-cbcd4d09f496"),
                            Author = "Andy Weir",
                            Genre = 1,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = new Guid("f15ea439-f2a1-40ac-8278-1056d7a75a52"),
                            Author = "Frank Herbert",
                            Genre = 0,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = new Guid("1192f7d6-3197-4a88-87ce-a251dd1cf0b3"),
                            Author = "Patrick Rothfuss",
                            Genre = 0,
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = new Guid("8be4237a-cadb-4f8c-bfd8-68eab7b7c64e"),
                            Author = "Harper Lee",
                            Genre = 6,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("3b57c8d7-a88e-4318-b5c4-0d1ab176c2e1"),
                            Author = "Jane Austen",
                            Genre = 3,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("023fe09a-5ed3-4b7c-8eeb-f323f9e43cbf"),
                            Author = "F. Scott Fitzgerald",
                            Genre = 3,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("b6680038-dd42-4e75-9b24-ab7f2455393d"),
                            Author = "Fyodor Dostoevsky",
                            Genre = 8,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("7a183b2a-9af9-4412-9a2d-bcac7383e7ac"),
                            Author = "J.D. Salinger",
                            Genre = 6,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("d292d10e-8797-4b79-be46-150c747a58bf"),
                            Author = "Bram Stoker",
                            Genre = 4,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = new Guid("905974f8-f5b3-4eaf-a143-11b8345aca92"),
                            Author = "Ray Bradbury",
                            Genre = 1,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = new Guid("7f7663d2-b426-4b01-af52-8d617a2fe553"),
                            Author = "Martin Fowler",
                            Genre = 7,
                            Title = "Refactoring"
                        });
                });

            modelBuilder.Entity("Web_Library.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f71797dc-7130-48d6-8f30-7d24d19bf347"),
                            Address = "Sofia, Mladost 1",
                            Age = 26,
                            Email = "ivan.petrov@library.bg",
                            FirstName = "Ivan",
                            IsBlocked = false,
                            LastName = "Petrov",
                            PhoneNumber = "+359888123456"
                        },
                        new
                        {
                            Id = new Guid("19c4ebff-4f5c-4504-8641-0dd4fb9f2218"),
                            Address = "Sofia, Lozenets",
                            Age = 32,
                            Email = "maria.georgieva@library.bg",
                            FirstName = "Maria",
                            IsBlocked = false,
                            LastName = "Georgieva",
                            PhoneNumber = "+359887654321"
                        },
                        new
                        {
                            Id = new Guid("30460549-2e0d-40c7-90ff-6f435900d186"),
                            Address = "Sofia, Nadezhda",
                            Age = 41,
                            Email = "georgi.ivanov@library.bg",
                            FirstName = "Georgi",
                            IsBlocked = true,
                            LastName = "Ivanov",
                            PhoneNumber = "+359889777888"
                        },
                        new
                        {
                            Id = new Guid("e6df1540-5bab-4126-b284-4a9af52c47cd"),
                            Address = "Sofia, Studentski Grad",
                            Age = 29,
                            Email = "elena.dimitrova@library.bg",
                            FirstName = "Elena",
                            IsBlocked = false,
                            LastName = "Dimitrova",
                            PhoneNumber = "+359886333444"
                        },
                        new
                        {
                            Id = new Guid("b97533fb-a904-4f0e-bacc-1dfd9f769122"),
                            Address = "Sofia, Krasno Selo",
                            Age = 35,
                            Email = "nikolay.stoyanov@library.bg",
                            FirstName = "Nikolay",
                            IsBlocked = false,
                            LastName = "Stoyanov",
                            PhoneNumber = "+359885999000"
                        },
                        new
                        {
                            Id = new Guid("70d6692c-73ff-42fd-8992-1e175692b52f"),
                            Address = "Sofia, Druzhba 2",
                            Age = 23,
                            Email = "petya.koleva@library.bg",
                            FirstName = "Petya",
                            IsBlocked = false,
                            LastName = "Koleva",
                            PhoneNumber = "+359884222333"
                        },
                        new
                        {
                            Id = new Guid("376b646e-7761-428b-b62b-21c58734fca7"),
                            Address = "Sofia, Obelya",
                            Age = 46,
                            Email = "dimitar.hristov@library.bg",
                            FirstName = "Dimitar",
                            IsBlocked = true,
                            LastName = "Hristov",
                            PhoneNumber = "+359883111222"
                        },
                        new
                        {
                            Id = new Guid("5c80ef3a-faad-40f4-b245-45790594fe37"),
                            Address = "Sofia, Geo Milev",
                            Age = 30,
                            Email = "radostina.nikolova@library.bg",
                            FirstName = "Radostina",
                            IsBlocked = false,
                            LastName = "Nikolova",
                            PhoneNumber = "+359882444555"
                        },
                        new
                        {
                            Id = new Guid("66757a02-9ffa-4c13-8070-6aeb39d5a570"),
                            Address = "Sofia, Lyulin 5",
                            Age = 34,
                            Email = "vladimir.angelov@library.bg",
                            FirstName = "Vladimir",
                            IsBlocked = false,
                            LastName = "Angelov",
                            PhoneNumber = "+359881666777"
                        },
                        new
                        {
                            Id = new Guid("7023f574-e36a-4c31-b4a0-65bba3947199"),
                            Address = "Sofia, Center",
                            Age = 27,
                            Email = "desislava.popova@library.bg",
                            FirstName = "Desislava",
                            IsBlocked = false,
                            LastName = "Popova",
                            PhoneNumber = "+359880888999"
                        });
                });

            modelBuilder.Entity("Web_Library.Models.UserBook", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("PickUpDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReservationExpiresOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReservedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UsersBooks");
                });

            modelBuilder.Entity("Web_Library.Models.UserBook", b =>
                {
                    b.HasOne("Web_Library.Models.Book", "Book")
                        .WithMany("BookUsers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Library.Models.User", "User")
                        .WithMany("UserBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Library.Models.Book", b =>
                {
                    b.Navigation("BookUsers");
                });

            modelBuilder.Entity("Web_Library.Models.User", b =>
                {
                    b.Navigation("UserBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
